services:
  - type: web
    name: symfony-app
    env: php
    plan: free
    buildCommand: |
      set -e
      curl -s https://getcomposer.org/installer | php
      php composer.phar install --no-dev --optimize-autoloader
      php bin/console assets:install public --env=prod --no-debug
      php bin/console cache:clear --env=prod --no-debug
    startCommand: symfony server:start --port=$PORT --no-tls
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: mysql-db
          property: connectionString

databases:
  - name: mysql-db
    plan: free
    databaseName: stage
    user: render_user
